t = "TGCTTTGACTATGTGTTATAAAGTGTACCACGTATACCAATCCTCTTTCTGTACACTGGTAAGGCCGCACCCGAGGTGACTGTCTTTGACAGTGCGGCACCTATGGGTAACCGAATCTACATGTGGCCCAGACAGTGCTCGGCGCAACGAGGTTAGGACGAGGCACCCCACGGGTAAAGAACTTTCAATTCACAGCGTAGGAGAAGCTGGGTGCATCCGCCACACAGTGAACCCGTCCGGCCGTGAGTTCGTAAAGAGCCCATGCTGAGGATCCATCGTAGAAAACCCCGTACGCCACCTCTTTGGAACAAGTTCTTGGGACCGGGCGCGAGCGCACAGCCGTTGTCTTTGAGGATCTACGTTTGGATCGTGATCGCTAATCCGCCAATTTTCAGAAGCCCCCCAAATCTGTGGAGGTCGTGTTTAAAAATCGGCAACGAGCGTATGATTGAGCCATTCTTAACCATGGGTGCATTAGAGTAAGCCGTCCATAGAGCCCAGTACAAGCGTGGTTCATATGGTTTTGTGTCGGGGCCGGTGAACTACTTACGACAAGGAGTGCTAGGTGCGTTCACACTCTCGTACGAGGCGACTCGTACCATCCAAAGGGTGGATATTTCTCTAGGCCAGGCAGGGACTCGAAGTGTGTCGTCCTGCCAGGCCTGGCGAAGCCGTTATGACCTTGGAGTCTCCCTCCCCGTTTCACGCCCTGACGGGTCAGCTGGTTAGGACCAGAGCGCTAGTGCGCCCACCCTACTAATTACCTGCTTGGCAGTTTCCCAGTCGTAGTCTGCACCGTCTGGGCCGGAAATTCGGCGGTTTGCCATGCGCGATATAAAAAGCCATGTTAGGTAGCAGCCATTGATTTTTTCTCAACGGCTCATTGGCCTATCGCTGAGCCCTGACGAGGAACCACACTAAATTAAATAGTGTAACAATACTCGCGAAAGTACGTGGGGCGCGGAGTTGAGGCCCATGATCCATACTCAA"
# u = ""
for i in range(len(t)):
    if t[i] == "T":
        # u = ''.join("U")
        print("U", end="")
    else:
        # u = ''.join(t[i])
        print(t[i], end="")
print("")

# Biopython verze
from Bio.Seq import Seq

dna_seq = Seq("TATAATAGACATG")
rna_seq = dna_seq.transcribe()

print(rna_seq)
